# This docker compose file is intended for setting up an environment for local
# development
version: '3.4'
services:
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: microservice
    volumes:
      - ./src:/app/server/src
      - ./tsconfig.json:/app/server/tsconfig.json
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    networks:
      - fastify-test

networks:
  fastify-test:
    external:
      name: fastify-test-network
